## creating a dataset with pandas

In [9]:
import pandas as pd

In [10]:
#Creating a dataframe with lists inside a dict

data= {'company':['skoda','honda','mahindra'],
      'model':['kushaq','civic','thar'],
      'year':[2020,2020,2020],
      'cc':[1498,1799,1997],
       'type':['petrol','petrol','petrol'],
       'price':['20L','20L','16.5L']}
df=pd.DataFrame(data)
df

    company   model  year    cc    type  price
0     skoda  kushaq  2020  1498  petrol    20L
1     honda   civic  2020  1799  petrol    20L
2  mahindra    thar  2020  1997  petrol  16.5L

In [11]:
#saving the dataframe as 'vehicles.csv' file with no specific index

df.to_csv('vehicles.csv',index=None)

In [12]:
#loading the data as 'vehicles.csv'

veh=pd.read_csv('/users/bhargavdamarla/1ds_python/vehicles.csv')
veh

    company   model  year    cc    type  price
0     skoda  kushaq  2020  1498  petrol    20L
1     honda   civic  2020  1799  petrol    20L
2  mahindra    thar  2020  1997  petrol  16.5L

## creating a dataset using public api

In [1]:
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest' 
#Original Sandbox Environment: 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'5000',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': '0ad53085-1cb2-4eb8-ad9e-3ffbd7e56509',
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  #print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)

In [2]:
type(data)

dict

In [3]:
import pandas as pd


#This allows you to see all the columns, not just like 15
df= pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

In [4]:
#This normalizes the data and makes it all pretty in a dataframe

df= pd.json_normalize(data['data'])

In [5]:
df

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address
0,1,Bitcoin,BTC,bitcoin,10686,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.958144e+07,19581443,False,NaN,1,NaN,NaN,NaN,2023-12-26T14:43:00.000Z,4.269184e+04,2.563853e+10,19.3193,-0.142748,-2.257987,0.165955,14.026974,25.730710,62.885641,8.359678e+11,50.2330,8.965286e+11,NaN,2023-12-26T14:43:00.000Z,NaN,NaN,NaN,NaN,NaN
1,1027,Ethereum,ETH,ethereum,8113,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.201839e+08,120183898.844562,True,NaN,2,NaN,NaN,NaN,2023-12-26T14:43:00.000Z,2.244316e+03,9.458723e+09,14.1015,-0.187151,-1.971419,1.752879,8.457403,26.136739,40.492354,2.697307e+11,16.2114,2.697307e+11,NaN,2023-12-26T14:43:00.000Z,NaN,NaN,NaN,NaN,NaN
2,825,Tether USDt,USDT,tether,69718,2015-02-25T00:00:00.000Z,"[payments, stablecoin, asset-backed-stablecoin...",NaN,9.132594e+10,94603058351.448959,True,NaN,3,NaN,NaN,NaN,2023-12-26T14:42:00.000Z,9.998596e-01,5.610668e+10,15.0731,-0.001340,-0.037575,0.040195,-0.013091,-0.022507,0.075346,9.131312e+10,5.4870,9.458978e+10,NaN,2023-12-26T14:42:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7
3,5426,Solana,SOL,solana,563,2020-04-10T00:00:00.000Z,"[pos, platform, solana-ecosystem, cms-holdings...",NaN,4.288534e+08,565719997.929135,True,NaN,4,NaN,NaN,NaN,2023-12-26T14:42:00.000Z,1.139295e+02,6.713291e+09,49.7384,-1.440143,-1.606196,53.651546,99.326629,253.440293,501.032872,4.885905e+10,2.9365,6.445218e+10,NaN,2023-12-26T14:42:00.000Z,NaN,NaN,NaN,NaN,NaN
4,1839,BNB,BNB,bnb,1921,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,1.516934e+08,151693443.552291,False,NaN,5,NaN,NaN,NaN,2023-12-26T14:42:00.000Z,3.007975e+02,1.575206e+09,100.8206,-0.441487,12.545254,19.806571,29.515893,33.010357,41.734720,4.562900e+10,2.7431,4.562900e+10,NaN,2023-12-26T14:42:00.000Z,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,19958,Snail Trail,SLIME,snail-trail,3,2022-05-04T22:43:30.000Z,"[gaming, avalanche-ecosystem, animal-racing]",3.000000e+08,0.000000e+00,300000000,False,NaN,4996,1.162460e+08,7.070726e+05,NaN,2023-12-26T14:42:00.000Z,6.082552e-03,4.174311e+03,-12.6008,-2.457986,-7.937562,9.595867,128.414393,527.181222,597.398539,0.000000e+00,0.0000,1.824766e+06,NaN,2023-12-26T14:42:00.000Z,5805.0,Avalanche C-Chain,AVAX,avalanche,0x5a15Bdcf9a3A8e799fa4381E666466a516F2d9C8
4996,12895,Lil Floki,LILFLOKI,lil-floki,15,2021-10-19T20:43:11.000Z,[],1.000000e+15,0.000000e+00,872876050604093,False,NaN,4997,8.728761e+14,1.880959e+05,NaN,2023-12-26T14:42:00.000Z,2.154898e-10,4.166779e+03,455.3609,-3.216137,12.026567,4.278056,108.597932,253.634768,405.825001,0.000000e+00,0.0000,2.154898e+05,NaN,2023-12-26T14:42:00.000Z,1839.0,BNB Smart Chain (BEP20),BNB,bnb,0x3271d12d5ba36b6582fafa029598fee0f5f6db35
4997,28061,SHIB2,SHIB2,shib2,1,2023-09-20T04:09:48.000Z,"[memes, ethereum-ecosystem]",1.000000e+09,0.000000e+00,1000000000,False,NaN,4998,1.000000e+09,5.177897e+05,NaN,2023-12-26T14:42:00.000Z,5.177897e-04,4.142220e+03,-40.2764,14.493705,21.267474,25.736318,16.205825,-49.471088,-53.257280,0.000000e+00,0.0000,5.177897e+05,NaN,2023-12-26T14:42:00.000Z,1027.0,Ethereum,ETH,ethereum,0x2dE7B02Ae3b1f11d51Ca7b2495e9094874A064c0
4998,5792,Bananatok,BNA,bananatok,6,2020-07-01T00:00:00.000Z,[],2.800000e+09,0.000000e+00,1800000000,False,NaN,4999,1.800000e+09,1.984101e+06,NaN,2023-12-26T14:42:00.000Z,1.102279e-03,4.131957e+03,-13.9100,-0.012637,-7.301820,-6.799229,-4.177901,-16.975319,-47.115445,0.000000e+00,0.0000,3.086380e+06,NaN,2023-12-26T14:42:00.000Z,1027.0,Ethereum,ETH,ethereum,0x20910e5b5f087f6439dfcb0dda4e27d1014ac2b8
4999,17429,Puff,PUFF,puff,7,2022-01-18T08:40:44.000Z,[],NaN,0.000000e+00,420000000,False,NaN,5000,NaN,NaN,NaN,2023-12-26T14:43:00.000Z,5.872615e-03,4.109741e+03,43.6522,-0.407409,1.494404,-9.737021,63.278559,156.203496,132.711109,0.000000e+00,0.0000,2.466498e+06,NaN,2023-12-26T14:43:00.000Z,5426.0,Solana,SOL,solana,G9tt98aYSznRk7jWsfuz9FnTdokxS6Brohdo9hSmjTRB

In [6]:
#saving the datafrme as 'coins.csv' file with no index

df.to_csv('coins.csv',index=None)

In [7]:
coins=pd.read_csv('/users/bhargavdamarla/1ds_python/coins.csv')
coins.head()

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address
0,1,Bitcoin,BTC,bitcoin,10686,2010-07-13T00:00:00.000Z,"['mineable', 'pow', 'sha-256', 'store-of-value...",21000000.0,1.958144e+07,1.958144e+07,False,NaN,1,NaN,NaN,NaN,2023-12-26T14:43:00.000Z,42691.835971,2.563853e+10,19.3193,-0.142748,-2.257987,0.165955,14.026974,25.730710,62.885641,8.359678e+11,50.2330,8.965286e+11,NaN,2023-12-26T14:43:00.000Z,NaN,NaN,NaN,NaN,NaN
1,1027,Ethereum,ETH,ethereum,8113,2015-08-07T00:00:00.000Z,"['pos', 'smart-contracts', 'ethereum-ecosystem...",NaN,1.201839e+08,1.201839e+08,True,NaN,2,NaN,NaN,NaN,2023-12-26T14:43:00.000Z,2244.316370,9.458723e+09,14.1015,-0.187151,-1.971419,1.752879,8.457403,26.136739,40.492354,2.697307e+11,16.2114,2.697307e+11,NaN,2023-12-26T14:43:00.000Z,NaN,NaN,NaN,NaN,NaN
2,825,Tether USDt,USDT,tether,69718,2015-02-25T00:00:00.000Z,"['payments', 'stablecoin', 'asset-backed-stabl...",NaN,9.132594e+10,9.460306e+10,True,NaN,3,NaN,NaN,NaN,2023-12-26T14:42:00.000Z,0.999860,5.610668e+10,15.0731,-0.001340,-0.037575,0.040195,-0.013091,-0.022507,0.075346,9.131312e+10,5.4870,9.458978e+10,NaN,2023-12-26T14:42:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7
3,5426,Solana,SOL,solana,563,2020-04-10T00:00:00.000Z,"['pos', 'platform', 'solana-ecosystem', 'cms-h...",NaN,4.288534e+08,5.657200e+08,True,NaN,4,NaN,NaN,NaN,2023-12-26T14:42:00.000Z,113.929470,6.713291e+09,49.7384,-1.440143,-1.606196,53.651546,99.326629,253.440293,501.032872,4.885905e+10,2.9365,6.445218e+10,NaN,2023-12-26T14:42:00.000Z,NaN,NaN,NaN,NaN,NaN
4,1839,BNB,BNB,bnb,1921,2017-07-25T00:00:00.000Z,"['marketplace', 'centralized-exchange', 'payme...",NaN,1.516934e+08,1.516934e+08,False,NaN,5,NaN,NaN,NaN,2023-12-26T14:42:00.000Z,300.797460,1.575206e+09,100.8206,-0.441487,12.545254,19.806571,29.515893,33.010357,41.734720,4.562900e+10,2.7431,4.562900e+10,NaN,2023-12-26T14:42:00.000Z,NaN,NaN,NaN,NaN,NaN